In [7]:
import numpy as np
import pandas as pd
import sklean.model_selection as train_test_split

ModuleNotFoundError: No module named 'sklean'

In [8]:
import sklearn.model_selection as train_test_split

In [9]:
df = pd.read_csv('new_data.csv')

In [10]:
df

21.0  0.16777215  0.16777215.1  0.16777215.2  0.16777215.3  0.16777215.4  \
0   21.0    0.167772      0.167772      0.167772      0.167772      0.167772   
1   21.0    0.167772      0.167772      0.167772      0.167772      0.167772   
2    1.0    0.167772      0.167772      0.167772      0.167772      0.167772   
3   21.0    0.167772      0.167772      0.167772      0.167772      0.167772   
4   21.0    0.167772      0.167772      0.167772      0.167772      0.167772   
5   21.0    0.167772      0.167772      0.167772      0.167772      0.167772   
6   54.0    0.167772      0.167772      0.167772      0.167772      0.167772   
7    1.0    0.167772      0.167772      0.167772      0.167772      0.167772   
8   54.0    0.167772      0.167772      0.167772      0.167772      0.167772   
9    1.0    0.167772      0.167772      0.167772      0.167772      0.167772   
10  21.0    0.167772      0.167772      0.167772      0.167772      0.167772   
11  54.0    0.167772      0.167772      0.167772      0.167772      0.167772   
12   1.0    0.167772      0.167772      0.167772      0.167772      0.167772   
13  21.0    0.167772      0.167772      0.167772      0.167772      0.167772   
14   1.0    0.167772      0.167772      0.167772      0.167772      0.167772   
15  54.0    0.167772      0.167772      0.167772      0.167772      0.167772   
16   1.0    0.167772      0.167772      0.167772      0.167772      0.167772   
17  54.0    0.167772      0.167772      0.167772      0.167772      0.167772   
18  54.0    0.167772      0.167772      0.167772      0.167772      0.167772   
19  54.0    0.167772      0.167772      0.167772      0.167772      0.167772   
20   1.0    0.167772      0.167772      0.167772      0.167772      0.167772   
21   1.0    0.167772      0.167772      0.167772      0.167772      0.167772   
22   1.0    0.167772      0.167772      0.167772      0.167772      0.167772   
23  54.0    0.167772      0.167772      0.167772      0.167772      0.167772   
24  54.0    0.167772      0.167772      0.167772      0.167772      0.167772   
25  21.0    0.167772      0.167772      0.167772      0.167772      0.167772   
26   1.0    0.167772      0.167772      0.167772      0.167772      0.167772   
27  54.0    0.167772      0.167772      0.167772      0.167772      0.167772   
28  21.0    0.167772      0.167772      0.167772      0.167772      0.167772   

    0.16777215.5  0.16777215.6  0.16777215.7  0.16777215.8  ...  \
0       0.167772      0.167772      0.167772      0.167772  ...   
1       0.167772      0.167772      0.167772      0.167772  ...   
2       0.167772      0.167772      0.167772      0.167772  ...   
3       0.167772      0.167772      0.167772      0.167772  ...   
4       0.167772      0.167772      0.167772      0.167772  ...   
5       0.167772      0.167772      0.167772      0.167772  ...   
6       0.167772      0.167772      0.167772      0.167772  ...   
7       0.167772      0.167772      0.167772      0.167772  ...   
8       0.167772      0.167772      0.167772      0.167772  ...   
9       0.167772      0.167772      0.167772      0.167772  ...   
10      0.167772      0.167772      0.167772      0.167772  ...   
11      0.167772      0.167772      0.167772      0.167772  ...   
12      0.167772      0.167772      0.167772      0.167772  ...   
13      0.167772      0.167772      0.167772      0.167772  ...   
14      0.167772      0.167772      0.167772      0.167772  ...   
15      0.167772      0.167772      0.167772      0.167772  ...   
16      0.167772      0.167772      0.167772      0.167772  ...   
17      0.167772      0.167772      0.167772      0.167772  ...   
18      0.167772      0.167772      0.167772      0.167772  ...   
19      0.167772      0.167772      0.167772      0.167772  ...   
20      0.167772      0.167772      0.167772      0.167772  ...   
21      0.167772      0.167772      0.167772      0.167772  ...   
22      0.167772      0.167772      0.167772      0.167772  ..

In [11]:
X = np.array(df.drop(df.column[0], axis=1))
Y = np.array(df.iloc[:,0])

AttributeError: 'DataFrame' object has no attribute 'column'

In [12]:
X = np.array(df.drop(df.columns[0], axis=1))
Y = np.array(df.iloc[:,0])

In [13]:
X

array([[0.16777215, 0.16777215, 0.16777215, ..., 0.16777215, 0.16777215,
        0.16777215],
       [0.16777215, 0.16777215, 0.16777215, ..., 0.16777215, 0.16777215,
        0.16777215],
       [0.16777215, 0.16777215, 0.16777215, ..., 0.16777215, 0.16777215,
        0.16777215],
       ...,
       [0.16777215, 0.16777215, 0.16777215, ..., 0.16777215, 0.16777215,
        0.16777215],
       [0.16777215, 0.16777215, 0.16777215, ..., 0.16777215, 0.16777215,
        0.16777215],
       [0.16777215, 0.16777215, 0.16777215, ..., 0.16777215, 0.16777215,
        0.16777215]])

In [14]:
Y

array([21., 21.,  1., 21., 21., 21., 54.,  1., 54.,  1., 21., 54.,  1.,
       21.,  1., 54.,  1., 54., 54., 54.,  1.,  1.,  1., 54., 54., 21.,
        1., 54., 21.])

In [15]:
X

array([[0.16777215, 0.16777215, 0.16777215, ..., 0.16777215, 0.16777215,
        0.16777215],
       [0.16777215, 0.16777215, 0.16777215, ..., 0.16777215, 0.16777215,
        0.16777215],
       [0.16777215, 0.16777215, 0.16777215, ..., 0.16777215, 0.16777215,
        0.16777215],
       ...,
       [0.16777215, 0.16777215, 0.16777215, ..., 0.16777215, 0.16777215,
        0.16777215],
       [0.16777215, 0.16777215, 0.16777215, ..., 0.16777215, 0.16777215,
        0.16777215],
       [0.16777215, 0.16777215, 0.16777215, ..., 0.16777215, 0.16777215,
        0.16777215]])

In [16]:
x_train,x_test,y_train,y_test = train_test_split(df, test_size=0.3)

TypeError: 'module' object is not callable

In [17]:
x_train,x_test,y_train,y_test = train_test_split(X,Y, test_size=0.3)

TypeError: 'module' object is not callable

In [18]:
x_train,x_test,y_train,y_test = train_test_split(X,Y, test_size=0.3)

TypeError: 'module' object is not callable

In [19]:
import sklearn

In [20]:
x_train,x_test,y_train,y_test = sklearn.model_selection.train_test_split(X,Y, test_size=0.3)

In [21]:
x_train

array([[0.16777215, 0.16777215, 0.16777215, ..., 0.16777215, 0.16777215,
        0.16777215],
       [0.16777215, 0.16777215, 0.16777215, ..., 0.16777215, 0.16777215,
        0.16777215],
       [0.16777215, 0.16777215, 0.16777215, ..., 0.16777215, 0.16777215,
        0.16777215],
       ...,
       [0.16777215, 0.16777215, 0.16777215, ..., 0.16777215, 0.16777215,
        0.16777215],
       [0.16777215, 0.16777215, 0.16777215, ..., 0.16777215, 0.16777215,
        0.16777215],
       [0.16777215, 0.16777215, 0.16777215, ..., 0.16777215, 0.16777215,
        0.16777215]])

In [22]:
x_train.info()

AttributeError: 'numpy.ndarray' object has no attribute 'info'

In [24]:
x_train.length

AttributeError: 'numpy.ndarray' object has no attribute 'length'

In [25]:
x_train.length()

AttributeError: 'numpy.ndarray' object has no attribute 'length'

In [26]:
x_train.size()

TypeError: 'int' object is not callable

In [27]:
x_train.size

81920

In [28]:
x_test.size

36864

In [29]:
y_train.size

20

In [30]:
y_test.size

9

In [31]:
from sklearn.neighbors import KNeighborsClassifier

In [32]:
model = KNeighborsClassifier(n_neighbors=3)

In [33]:
model.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [34]:
acc = model.score(x_test,y_test)

In [35]:
acc

0.6666666666666666

In [36]:
predicted = model.predict(x_test)

In [37]:
predicted

array([54., 54., 21.,  1.,  1.,  1.,  1., 54., 54.])

In [38]:
chars = { 1.0: 'අ', 21.0: 'ක', 54: 'ව' }

In [39]:
for i in range(len(predicted)):
    print("predicted : ", chars[predicted[i]], "Actual : ", chars[y_test[i]]) 

predicted :  ව Actual :  ව
predicted :  ව Actual :  ක
predicted :  ක Actual :  ක
predicted :  අ Actual :  අ
predicted :  අ Actual :  අ
predicted :  අ Actual :  ක
predicted :  අ Actual :  අ
predicted :  ව Actual :  ක
predicted :  ව Actual :  ව
